package gui;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Hyperlink;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

public class HoofdStatistiekenController {
	@FXML
	private HBox contentBox;
	@FXML
	private Button btnSessies;
	@FXML
	private Button btnGebruikers;
	@FXML
	private VBox lijstBox;
	@FXML
	private Label lblCategorie;
	@FXML
	private Hyperlink linkPowerBI;

	// Event Listener on Button[#btnSessies].onAction
	@FXML
	public void toonSessielijst(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btnGebruikers].onAction
	@FXML
	public void toonGebruikerslijst(ActionEvent event) {
		// TODO Autogenerated
	}

	@FXML
	void goToPowerBI(ActionEvent event) {

		if (Desktop.isDesktopSupported()) {
			try {
				Desktop	.getDesktop()
						.browse(new URI("https://powerbi.microsoft.com/nl-nl/"));
			} catch (IOException e1) {
				e1.printStackTrace();
			} catch (URISyntaxException e1) {
				e1.printStackTrace();
			}
		}
	}

}
